services:
  schedules:
    build:
      context: ../../
      dockerfile: ./microservices/schedules/Dockerfile
      target: prod
    env_file:
      - .env
    depends_on:
      schedules-db:
        condition: service_healthy
    healthcheck:
      test: node ./healthcheck.js
      timeout: 10s
      start_period: 15s

  schedules-db:
    build:
      context: ./database
    env_file:
      - ./database/.env
    volumes:
      - schedules-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s

volumes:
  schedules-db-data:
