# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import schedules_pb2 as schedules__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in schedules_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Find = channel.unary_unary(
                '/schedule.SchedulesService/Find',
                request_serializer=schedules__pb2.SchedulesFindRequest.SerializeToString,
                response_deserializer=schedules__pb2.SchedulesFindResponse.FromString,
                _registered_method=True)
        self.FindOne = channel.unary_unary(
                '/schedule.SchedulesService/FindOne',
                request_serializer=schedules__pb2.SchedulesFindOneRequest.SerializeToString,
                response_deserializer=schedules__pb2.Schedule.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/schedule.SchedulesService/Create',
                request_serializer=schedules__pb2.SchedulesCreateRequest.SerializeToString,
                response_deserializer=schedules__pb2.Schedule.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/schedule.SchedulesService/Update',
                request_serializer=schedules__pb2.SchedulesUpdateRequest.SerializeToString,
                response_deserializer=schedules__pb2.Schedule.FromString,
                _registered_method=True)
        self.Remove = channel.unary_unary(
                '/schedule.SchedulesService/Remove',
                request_serializer=schedules__pb2.SchedulesRemoveRequest.SerializeToString,
                response_deserializer=schedules__pb2.Schedule.FromString,
                _registered_method=True)


class SchedulesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindOne(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Find': grpc.unary_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=schedules__pb2.SchedulesFindRequest.FromString,
                    response_serializer=schedules__pb2.SchedulesFindResponse.SerializeToString,
            ),
            'FindOne': grpc.unary_unary_rpc_method_handler(
                    servicer.FindOne,
                    request_deserializer=schedules__pb2.SchedulesFindOneRequest.FromString,
                    response_serializer=schedules__pb2.Schedule.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=schedules__pb2.SchedulesCreateRequest.FromString,
                    response_serializer=schedules__pb2.Schedule.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=schedules__pb2.SchedulesUpdateRequest.FromString,
                    response_serializer=schedules__pb2.Schedule.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=schedules__pb2.SchedulesRemoveRequest.FromString,
                    response_serializer=schedules__pb2.Schedule.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schedule.SchedulesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('schedule.SchedulesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.SchedulesService/Find',
            schedules__pb2.SchedulesFindRequest.SerializeToString,
            schedules__pb2.SchedulesFindResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.SchedulesService/FindOne',
            schedules__pb2.SchedulesFindOneRequest.SerializeToString,
            schedules__pb2.Schedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.SchedulesService/Create',
            schedules__pb2.SchedulesCreateRequest.SerializeToString,
            schedules__pb2.Schedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.SchedulesService/Update',
            schedules__pb2.SchedulesUpdateRequest.SerializeToString,
            schedules__pb2.Schedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.SchedulesService/Remove',
            schedules__pb2.SchedulesRemoveRequest.SerializeToString,
            schedules__pb2.Schedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
