# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import schedule_generation_pb2 as schedule__generation__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in schedule_generation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleGenerationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSchedule = channel.unary_unary(
                '/schedule_generation.ScheduleGenerationService/GenerateSchedule',
                request_serializer=schedule__generation__pb2.ScheduleGenerationRequest.SerializeToString,
                response_deserializer=schedule__generation__pb2.ScheduleGenerationResponse.FromString,
                _registered_method=True)


class ScheduleGenerationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleGenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSchedule,
                    request_deserializer=schedule__generation__pb2.ScheduleGenerationRequest.FromString,
                    response_serializer=schedule__generation__pb2.ScheduleGenerationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schedule_generation.ScheduleGenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('schedule_generation.ScheduleGenerationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScheduleGenerationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule_generation.ScheduleGenerationService/GenerateSchedule',
            schedule__generation__pb2.ScheduleGenerationRequest.SerializeToString,
            schedule__generation__pb2.ScheduleGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
