services:
  notifications:
    build:
      context: ../../
      dockerfile: ./microservices/notifications/Dockerfile
      target: prod
    env_file:
      - .env
    healthcheck:
      test: node ./healthcheck.js
      timeout: 10s
      start_period: 15s
    depends_on:
      notifications-db:
        condition: service_healthy

  notifications-db:
    build:
      context: ./database
    env_file:
      - ./database/.env
    volumes:
      - notifications-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 30s
      retries: 5
      start_period: 20s

volumes:
  notifications-db-data:
